apiVersion: v1
kind: Service
metadata:
  name: apps
spec:
  selector:
    app: apps
  type: NodePort
  ports:
    - name: http
      port: 8081
      nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps
spec:
  selector:
    matchLabels:
      app: apps
  replicas: 1
  template:
    metadata:
      labels:
        app: apps
    spec:
      containers:
        - name: server
          image: danyloshelepalo/apps:latest
          ports:
            - name: http
              containerPort: 8081