apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  selector:
    app: users
  type: NodePort
  ports:
    - name: http
      port: 8082
      nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  selector:
    matchLabels:
      app: users
  replicas: 1
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: server
          image: danyloshelepalo/users:latest
          ports:
            - name: http
              containerPort: 8082